version: '3'
services:

  dapp:
    container_name: overnight-dapp
    image: cr.yandex/crpg11k469bhc8lch9gm/overnight/dapp:1
    networks:
      - ovn
    ports:
      - 71:8080

  ganache:
    container_name: overnight-ganache
    image: trufflesuite/ganache-cli:latest
    ports:
      - "8555:8555"
    volumes:
      - ../ganache_poly:/ganache_data
    entrypoint:
      - node
      - /app/ganache-core.docker.cli.js
      - --db=/ganache_data
      - -p 8555
      - --mnemonic
      - 'clutch captain shoe salt awake harvest setup primary inmate ugly among become'
      - -g 20
      - -e 1000
      - --networkId
      - '137'


networks:
  ovn:
    external: true
